<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.076"
        timestamp="2024-12-26T21:34:59.479401-03:00" hostname="PCHumberto">
        <testcase classname="tests.test_pytest"
            name="test_quando_brincadeira_receber_1_entao_retornar_1" time="0.001" />
        <testcase classname="tests.test_pytest"
            name="test_quando_brincadeira_receber_2_entao_retornar_2" time="0.000" />
        <testcase classname="tests.test_pytest"
            name="test_quando_brincadeira_receber_3_entao_retornar_queijo" time="0.000" />
        <testcase classname="tests.test_pytest"
            name="test_quando_brincadeira_receber_5_entao_retornar_goiabada" time="0.001">
            <failure
                message="AssertionError: assert 'goiabada' == 'goiabadaa'&#10;  &#10;  - goiabadaa&#10;  ?         -&#10;  + goiabada">def
                test_quando_brincadeira_receber_5_entao_retornar_goiabada():
                &gt; assert brincadeira(5) == 'goiabadaa'
                E AssertionError: assert 'goiabada' == 'goiabadaa'
                E
                E - goiabadaa
                E ? -
                E + goiabada

                tests\test_pytest.py:42: AssertionError</failure>
        </testcase>
    </testsuite>
</testsuites>